#!/usr/bin/env python3
"""Assemble the standalone pages in the repo root from src/.

Each template in src/pages/ is a complete page with `/*@inline <path>*/`
tokens where a source file (fonts, runtime CSS/JS, compiler, book data)
gets embedded. The outputs are self-contained single files — no runtime
fetches — which is what GitHub Pages serves.

howwemet.html is a hand-crafted reconstruction and is not built.

Usage:  python3 build.py          # write index.html and player.html
        python3 build.py --check  # exit 1 if outputs are stale (CI)
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent

PAGES = {
    "src/pages/composer.html": "index.html",
    "src/pages/player.html": "player.html",
    "src/pages/viewer.html": "b.html",
    "src/pages/gallery.html": "gallery.html",
}

TOKEN = re.compile(r"/\*@inline ([^*]+?)\*/")

HEADER = "<!-- Generated by build.py from {src} — edit the sources in src/, then run `python3 build.py`. -->\n"


def build_page(src: str) -> str:
    text = (ROOT / src).read_text(encoding="utf-8")

    def inline(m: re.Match) -> str:
        path = ROOT / m.group(1).strip()
        if not path.is_file():
            sys.exit(f"error: {src} inlines missing file {m.group(1).strip()}")
        return path.read_text(encoding="utf-8")

    # Inlined files may themselves contain tokens (e.g. compile.js pulls the
    # generation contract from api/src/contract/). Resolve until stable.
    for _ in range(10):
        text, count = TOKEN.subn(inline, text)
        if count == 0:
            break
    else:
        sys.exit(f"error: {src} did not stabilize — inline cycle?")
    return HEADER.format(src=src) + text


def main() -> None:
    check = "--check" in sys.argv[1:]
    stale = []
    for src, dest in PAGES.items():
        built = build_page(src)
        out = ROOT / dest
        if check:
            if not out.is_file() or out.read_text(encoding="utf-8") != built:
                stale.append(dest)
        else:
            out.write_text(built, encoding="utf-8")
            print(f"{dest}  ({len(built):,} bytes)  <-  {src}")
    if stale:
        sys.exit(
            "stale build outputs: " + ", ".join(stale)
            + "\nRun `python3 build.py` and commit the results."
        )


if __name__ == "__main__":
    main()
